[variables]
main_domain = "${domain}"

# Secrets
postgres_password = "${password:32}"
jwt_secret = "${base64:64}"
secret_key_base = "${base64:64}"
anon_key = "${base64:32}"
service_role_key = "${base64:32}"
logflare_api_key = "${base64:32}"

[config]
[[config.domains]]
serviceName = "supabase-studio"
port = 3000
host = "supabase.${main_domain}"

[[config.domains]]
serviceName = "supabase-kong"
port = 8000
host = "api.${main_domain}"

[config.env]
# Supabase Configuration
POSTGRES_PASSWORD = "${postgres_password}"
POSTGRES_DB = "postgres"
JWT_SECRET = "${jwt_secret}"
JWT_EXPIRY = "3600"
SECRET_KEY_BASE = "${secret_key_base}"
ANON_KEY = "${anon_key}"
SERVICE_ROLE_KEY = "${service_role_key}"
LOGFLARE_API_KEY = "${logflare_api_key}"
PGRST_DB_SCHEMAS = "public,storage,graphql_public"
SUPABASE_PUBLIC_URL = "https://api.${main_domain}"
API_EXTERNAL_URL = "https://api.${main_domain}"
SITE_URL = "https://${main_domain}"
DASHBOARD_USERNAME = "${{project.ADMIN_USER}}"
DASHBOARD_PASSWORD = "${{project.ADMIN_PASSWORD}}"
STUDIO_DEFAULT_ORGANIZATION = "IA Stack"
STUDIO_DEFAULT_PROJECT = "ia-stack"
STORAGE_BACKEND = "file"

# Authentication
DISABLE_SIGNUP = "false"
ENABLE_EMAIL_SIGNUP = "true"
ENABLE_ANONYMOUS_USERS = "false"
ENABLE_EMAIL_AUTOCONFIRM = "false"

[[config.mounts]]
volumeName = "supabase-db-data"
mountPath = "/var/lib/postgresql/data"

[[config.mounts]]
volumeName = "supabase-storage-data"
mountPath = "/var/lib/storage"