services:
  open-notebook:
    image: lfnovo/open_notebook:latest
    restart: unless-stopped
    expose:
      - 8502
    environment:
      SURREAL_URL: ${{project.SURREAL_URL}}
      SURREAL_USER: root
      SURREAL_PASSWORD: ${{project.SURREAL_PASSWORD}}
      SURREAL_NAMESPACE: open_notebook
      SURREAL_DATABASE: staging
      # OpenAI Configuration
      OPENAI_API_KEY: ${{project.OPENAI_API_KEY}}
      OPENAI_API_BASE: ${{project.OPENAI_API_BASE}}
    volumes:
      - open-notebook-data:/app/data

volumes:
  open-notebook-data: