services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8000}:8000"
      - "${WS_PORT:-8001}:8001"
    command: "start --user root --pass ${SURREALDB_PASSWORD}"
    environment:
      SURREALDB_PASSWORD: "${SURREALDB_PASSWORD}"
      SURREALDB_USER: root
    volumes:
      - surrealdb-data:/data
    user: root
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://surrealdb:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  surrealdb-data: {}
