[variables]
main_domain = "${domain}"
surrealdb_password = "${password:16}"

[config]
[[config.domains]]
serviceName = "surrealdb"
port = 8000
host = "surrealdb.${main_domain}"

[[config.domains]]
serviceName = "surrealdb"
port = 8001
host = "surrealdb-ws.${main_domain}"

[config.env]
SURREALDB_PASSWORD = "${surrealdb_password}"
SURREALDB_USER = "root"

[[config.mounts]]
volumeName = "surrealdb-data"
mountPath = "/data"