services:
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    expose:
      - 7700
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  meilisearch-data: