[variables]
main_domain = "${domain}"
meili_master_key = "${password:32}"

[config]
[[config.domains]]
serviceName = "meilisearch"
port = 7700
host = "search.${main_domain}"

[config.env]
MEILI_MASTER_KEY = "${{project.MEILI_MASTER_KEY}}"
MEILI_NO_ANALYTICS = "true"

[[config.mounts]]
volumeName = "meilisearch-data"
mountPath = "/meili_data"