[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "kokoro-tts"
port = 8880
host = "tts.${main_domain}"

[[config.mounts]]
volumeName = "kokoro-models"
mountPath = "/app/models"