[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "whisper"
port = 9000
host = "stt.${main_domain}"

[[config.mounts]]
volumeName = "whisper-models"
mountPath = "/root/.cache/whisper"