[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "freshrss"
port = 80
host = "freshrss.${main_domain}"

[config.env]
ADMIN_EMAIL = "${{project.ADMIN_EMAIL}}"
ADMIN_PASSWORD = "${{project.ADMIN_PASSWORD}}"
TIMEZONE = "Europe/Paris"

[[config.mounts]]
volumeName = "freshrss-data"
mountPath = "/var/www/FreshRSS/data"

[[config.mounts]]
volumeName = "freshrss-extensions"
mountPath = "/var/www/FreshRSS/extensions"