services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.104.0
    restart: unless-stopped
    expose:
      - 5678
    environment:
      N8N_HOST: "${N8N_HOST}"
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: "https://${N8N_HOST}/"
      GENERIC_TIMEZONE: ${TIMEZONE:-Europe/Paris}
      N8N_SECURE_COOKIE: "false"
      # Database Configuration
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: "${POSTGRES_HOST}"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: "${POSTGRES_DB}"
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: "${POSTGRES_PASSWORD}"
      # OpenAI Configuration
      N8N_AI_OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data: {}