services:
  karakeep:
    build:
      context: https://github.com/karakeep-app/karakeep.git#main
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    environment:
      DATA_DIR: /data
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://${KARAKEEP_HOST}
      # External Meilisearch Configuration
      MEILI_ADDR: ${MEILI_ADDR}}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}}
      # Browser Configuration
      BROWSER_WEB_URL: http://chrome:9222
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}}
      OPENAI_BASE_URL: ${OPENAI_API_BASE}}
      # S3 Configuration
      ASSET_STORE_S3_ENDPOINT: ${S3_ENDPOINT}}
      ASSET_STORE_S3_REGION: ${S3_REGION}}
      ASSET_STORE_S3_BUCKET: ${S3_BUCKET}}
      ASSET_STORE_S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}}
      ASSET_STORE_S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}}
    volumes:
      - karakeep-data:/data
    depends_on:
      - chrome

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

volumes:
  karakeep-data: