[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "uptime-kuma"
port = 3001
host = "uptime.${main_domain}"

[[config.mounts]]
volumeName = "uptime-kuma-data"
mountPath = "/app/data"